[package]
name = "rubato"
version = "0.6.0"
authors = ["HEnquist <henrik.enquist@gmail.com>"]
description = "Asynchronous resampling library intended for audio data"
license = "MIT"
repository = "https://github.com/HEnquist/rubato"
keywords = ["interpolation", "resampling"]
categories = ["multimedia::audio"]
readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
realfft = "0.4.0"
num-complex = "0.3"
num-integer = "0.1.44"
num-traits = "0.2"

[dev-dependencies] 
env_logger = "0.7.1"
criterion = "0.3.3"
rand = "0.8.1"
num-traits = "0.2.14"

[[bench]]
name = "resamplers"
harness = false
